/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas.View;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import uas.Controller.MahasiswaController;
import uas.Controller.ProdiController;

/**
 *
 * @author User
 */
public class FormProdi extends javax.swing.JFrame {

    /**
     * Creates new form mahasiswaView
     */
    ProdiController prodiController;
    public FormProdi() {
        initComponents();
        prodiController = new ProdiController(this);
        prodiController.clear();
        prodiController.isiTabelProdi();                
    }

    public JTable getTabelProdi() {
        return tabelProdi;
    }

    public void setTabelProdi(JTable tabelProdi) {
        this.tabelProdi = tabelProdi;
    }

    public JTextField getTxtkdProdi() {
        return txtkdProdi;
    }

    public void setTxtkdProdi(JTextField txtkdProdi) {
        this.txtkdProdi = txtkdProdi;
    }

    public JComboBox getComJurusan() {
        return comJurusan;
    }

    public void setComJurusan(JComboBox comJurusan) {
        this.comJurusan = comJurusan;
    }

    public JComboBox getComprodi() {
        return comprodi;
    }

    public void setComprodi(JComboBox comprodi) {
        this.comprodi = comprodi;
    }
    
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkdProdi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProdi = new javax.swing.JTable();
        butupdate = new javax.swing.JButton();
        butinsert = new javax.swing.JButton();
        butdelete = new javax.swing.JButton();
        butexit = new javax.swing.JButton();
        butclear = new javax.swing.JButton();
        comprodi = new javax.swing.JComboBox();
        comJurusan = new javax.swing.JComboBox();

        jButton5.setText("jButton1");

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Tabel Prodi");

        jLabel2.setText("Kode Prodi");

        jLabel3.setText("Prodi");

        jLabel5.setText("Jurusan");

        tabelProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Prodi", "Prodi", "Jurusan"
            }
        ));
        tabelProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProdi);

        butupdate.setText("Update");
        butupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butupdateActionPerformed(evt);
            }
        });

        butinsert.setText("Insert");
        butinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butinsertActionPerformed(evt);
            }
        });

        butdelete.setText("Delete");
        butdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdeleteActionPerformed(evt);
            }
        });

        butexit.setText("Exit");
        butexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butexitActionPerformed(evt);
            }
        });

        butclear.setText("Clear");
        butclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butclearActionPerformed(evt);
            }
        });

        comprodi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "D-III Administrasi Bisnis\t", "D-III Akuntansi\t", "D-III Bahasa Inggris\t", "D-III Manajemen Informatika", "D-III Teknik Alat Berat\t", "D-III Teknik Elektronika\t", "D-III Teknik Komputer\t", "D-III Teknik Listrik", "D-III Teknik Mesin\t", "D-III Teknik Sipil\t", "D-III Teknik Telekomunikasi", "D-III Usaha Perjalanan Wisata", "D-IV Akuntansi\t", "D-IV Teknik Elektronika\t", "D-IV Manajemen Rekayasa Konstruksi\t", "D-IV Perencanaan Jalan Dan Jembatan\t", "D-IV Teknik Manufaktur\t", "D-IV Teknik Perencanaan Irigasi Dan Rawa", "D-IV Teknik Telekomunikasi", "D-IV Teknologi Rekayasa Perangkat Lunak", "D-IV Teknologi Rekayasa Instalasi Listrik" }));

        comJurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrasi Niaga ", "Akuntansi", "Bahasa Inggris", "Teknik Elektro", "Teknik Mesin", "Teknik Sipil", "Teknologi Informasi" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(butinsert)
                        .addGap(18, 18, 18)
                        .addComponent(butupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butclear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butexit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(53, 53, 53)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comprodi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtkdProdi))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkdProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butupdate)
                    .addComponent(butinsert)
                    .addComponent(butdelete)
                    .addComponent(butclear)
                    .addComponent(butexit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butinsertActionPerformed
        // TODO add your handling code here:
        prodiController.insert();
        prodiController.isiTabelProdi();
        
    }//GEN-LAST:event_butinsertActionPerformed

    private void butupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butupdateActionPerformed
        // TODO add your handling code here:
        prodiController.update();
        prodiController.isiTabelProdi();        
    }//GEN-LAST:event_butupdateActionPerformed

    private void butdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdeleteActionPerformed
        // TODO add your handling code here:
        prodiController.delete();
        prodiController.isiTabelProdi();        
    }//GEN-LAST:event_butdeleteActionPerformed

    private void butclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butclearActionPerformed
        // TODO add your handling code here:
        prodiController.clear();
    }//GEN-LAST:event_butclearActionPerformed

    private void butexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_butexitActionPerformed

    private void tabelProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdiMouseClicked
        // TODO add your handling code here:
        prodiController.onMouseClickTabelProdi();
    }//GEN-LAST:event_tabelProdiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butclear;
    private javax.swing.JButton butdelete;
    private javax.swing.JButton butexit;
    private javax.swing.JButton butinsert;
    private javax.swing.JButton butupdate;
    private javax.swing.JComboBox comJurusan;
    private javax.swing.JComboBox comprodi;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProdi;
    private javax.swing.JTextField txtkdProdi;
    // End of variables declaration//GEN-END:variables
}
